using System;
using System.Collections.ObjectModel;
using System.Threading.Tasks;
using AutoSchedule.Core.Models;
using System.Collections.Generic;
using Priority_Queue;
using PriorityQueue = Priority_Queue.SimplePriorityQueue<AutoSchedule.Core.Models.Session, AutoSchedule.Core.Models.Priority>;

namespace AutoSchedule.UI.Services
{
    public class AppDataService
    {
        /// <summary>
        /// Currently selected schedule.
        /// </summary>
        public Schedule CurrentSchedule = new();
        public readonly ObservableCollection<string> FilteredClasses = new();
        public readonly ObservableCollection<string> SelectedClasses = new();
        public Dictionary<string, Priority> Priorities = new();
        public PriorityQueue @PriorityQueue = new();
        /// <summary>
        /// All available schedules generated by ClassSelector.
        /// </summary>
        public readonly ObservableCollection<Schedule> AvailableSchedules = new();

        public string searchBoxText = string.Empty;

        /// <summary>
        /// Indicates whether the service is initialized.
        /// </summary>
        public bool initialized = false;

        public async Task InitializeAsync(AppDataServiceSingleton appDataServiceSingleton)
        {
            if (!initialized)
            {
                await appDataServiceSingleton.InitializeAsync();
                foreach (var item in appDataServiceSingleton.AvailableClasses) FilteredClasses.Add(item);
                initialized = true;

#if DEBUG
                Console.WriteLine("DataService initialized.");
#endif
            }
        }
    }
}
